name: yum
description: A Flutter application for recipe suggestions based on ingredients.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  image_picker: ^1.0.7
  provider: ^6.0.5
  shared_preferences: ^2.0.17
  json_annotation: ^4.8.0
  intl: ^0.19.0
  collection: ^1.17.0
  cached_network_image: ^3.2.3
  flutter_cache_manager: ^3.3.0
  url_launcher: ^6.1.9
  logger: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.3.3
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-Bold.ttf
          weight: 700